// prettier-ignore

export const comments = [
  'Bonne soirée bonne adresse repas correct service sympathique produits frais à conseiller fortement sympathique',
  'J’ai beaucoup aimé mangé a La Table de Colette c’était vraiment bon. Les employés très respectueux. Plat qui arrive rapidement',
  'Visité cet été entre 2 confinements ;-) Trés bonne cuisine et acceuil agréable. Prix corrects compte tenu de la qualité',
  'Belle hâte gastronomique, un menu surprise, cadre terrasse au calme et des personnes avec un service attentionné. Que demander de plus?',
  'Découverte d’un nouveau restaurant en ce dîner du 23 septembre : La Table de Colette. Et c’est peu de dire que c’est une jolie découverte',
  'Seconde visite à la table de Colette. Nous nous sommes encore régalés et avons passé un excellent moment. Le menu était encore surprenant (notamment un plat qui sublimait les brocolis). L’accord mets vins était parfait',
  'Nous avons passé un très bon moment gustatif. Le cadre est agréable et équipe chaleureuse',
  'Immense créativité, service sympathique et efficace. Bravo à toute léquipe. Nous avons pris le menu 7 plats. Je pense que 5 suffisent pour un appétit normal',
  'Les saveurs retrouvées, mais plus encore, les saveurs du moment, du lieu, aux antipodes de la nourriture fusion',
  'Excellente note de cet établissement qui est à la hauteur du plaisir gustatif ou devrais-je dire de lexpérience global. En effet le staff est aux petits soins, chaque plat est expliqué, ils répondent volontiers aux questions également',
  'Nous sommes venus fêter un anniversaire en famille et nous avons passé une excellente soirée. Nous avons pris le menu 7 plats et nous nous sommes tous régalés. Cuisine généreuse et inventive',
  'Locaux modernes très agréables. Service jeune, très professionnel , très efficace,tout en étant chaleureux et décontracté',
  'Tout est agréable dans ce restaurant, la décoration, le service, le menu. Un grand soin est apporté à la qualité des ingrédients et à leur provenance et les résultat est excellent',
  'Excellente soirée dans un cadre superbe, personnel très attentionné, cuisine raffinée nous reviendrons. Consignes sanitaires respectées.',
  'Cocktail aux crevettes avec une crevette avariée et obligation de recracher... Tartare avec morceaux de nerfs et sauce trop sucrée Café oublié...',
  'Accueil est chaleureux, le cadre est très typique de la brasserie parisienne haut de gamme, le service est hyper pro , aucune fausse note, un vrai plaisir de voir un travail de ce niveau , une cuisine excellente',
  'Accueil est satisfaisant. Pour les plats jespère être tombé sur un mauvais jour dimanche 16 aout. Les escargots étaient flasque et vinaigrés. Même le peu de sauce n\'était pas bonne.',
  'Accueil très sympathique, dans un cadre type brasserie. Une carte succulente et généreuse.',
  'Une valeur sûre. Plats brasserie : andouillette, filet de bœuf, entrecôte d’Angus, choucroute de poissons, huîtres.',
  'Ambiance parisienne,bonne carte,bon service, peut être une addition un peu élevé au regard des consommations....',
  'Personnel aimable, service sans trop d’attente. De bons plats à des prix « parisiens » corrects, selon les assiettes.',
  'Belle brasserie classique. Le lieu est chaleureux et le parking relativement facile aux alentours. Belle carte de brasserie avec de vrais plats qui tiennent au corps, et goûteux (salade de haricots vert au foie gras, blanquette, ...).',
  'Une honte! Le pot au feu de la semelle!! Sec et immangeable.. renvoyez en cuisine ( le garçon ne semblait pas du tout étonné)',
  'L’endroit est recherché et il faut réserver. À juste titre, car tout est bon, frais, goûteux. Service impeccable malgré le fait que, chaque midi, les deux services sont archi-complets',
  'Typique brasserie parisienne chic aux excellents produits. La cuisine est vraiment délicieuse, le service rapide et professionnel, la responsable d\'accueil parfaite et l\'ambiance formidable',
  'Tous les ans , nous nous retrouvons en famille dans cette jolie brasserie près du parc Monceau . Plateau de fruit de mer à partager , très belle cote de Bœuf pour 2 et blanquette de veau à l’ancienne excellente !!',
  'Hormis l’emplacement idéalement situé en face du Parc Monceau, cette brasserie n’offre aucun intérêt : accueil médiocre, plats industriels sans goût et prix prohibitifs. A éviter !',
  'Jamais déçu, la qualité est au rendez-vous dans un cadre très agréable. Très bonne salade pour un déjeuner sur le pouce',
  'Brasserie typique avec personnel aux petits soins. Très bons plats. La brioche perdue au caramel beurre salée est un délice. Je conseille vivement ... super cadre',
  'Salade césar : salade verte , salade verte et encore salade verte ( et en plus plutôt dure ) avec à peine un soupçon de sauce',
  'Brasserie dans la tradition mais tables un peu serrées ,bonne qualité des produits notamment des fruits de mer,à noter l\'excellent œufs "mayo" dans le choix des entrées et pour terminer',
  'J\'y ai été pour un déjeuner avec une amie. Accueil correcte et table serrée les unes aux autres.',
  'Et c’est déjà pas mal car dans le quartier on ne mange qu’en semaine Alors on nous tasse entre deux tables alors que plus de la moitié du restaurant est vide',
  'Cadre très sympa mais assiette décevante. Service laissant à desirer. J avais commandé une bavette saignante et on m a apporté une bien cuite',
  'Nous y sommes allés pour le dîner. J\'ai pris le steak avec de la sauce bernaise et c\'était bon',
  'Nous y avons mangé sur notre première journée à visiter Paris avec un autre couple. Nous avons besoin d\'un endroit où nous pouvions aller manger un peu tôt',
  'Dans la préparation de notre voyage à Paris, j\'ai lu plusieurs commentaires TripAdvisor et nous avons trouvé ce restaurant près de notre hôtel',
  'C\'était mon restaurant local quand je vivais à Paris. Un très sympathique et confortable pour venir pour boire un verre ou un repas.',
  'La nourriture était bonne et très bonne ambiance. Le service était excellent et tout parfaitement juste. J\'adorerais y retourner quand je vais à Paris l\'année prochaine.',
  'Après une promenade plus agréable à travers le Parc Monceau nous avons trouvé ce restaurant et nous nous sommes arrêtés pour un très léger au déjeuner',
  'Très belle brasserie près du Parc Monceau. La nourriture est bonne et les portions sont assez grandes, alors réfléchissez-y à deux fois avant de commander les entrées',
  'Nous sommes allés sur le Valois pour dîner ce soir sur la recommandation d\'un des membres du personnel de l\'hôtel où nous sommes restés à Paris.',
  'Il y a un super petit café de Paris. Nous avons apprécié la cuisine et l\'emplacement. Thomas le serveur était également excellent.',
  'La nourriture est tellement bon! Tout était très frais et originaux et classiques. La situation est formidable, tout près de l\'entrée du Parc Monceau',
  'Près du Parc Monceau, un jardin magnifique de belle capitale, est un endroit merveilleux pour déjeuner',
  'Nous avons toujours eu du mal à trouver de très authentique cuisine dans les restaurants de lieux touristiques de Paris. Nous sommes contents',
  'Ce restaurant a été recommandé par notre organisateur de notre hôtel et à un prix raisonnable. Elle avait l\'air d\'être fréquenté par la population locale. Leur "poulet jaune" ou le saumon',
  'Nous avons été en suivant l\'un des chemins dans un livre que nous avons acheté d\'infos sur les promenades à chacun des distritos municipales',
  'Ma femme et moi, ma nièce et moi-même avons passé le déjeuner dans cet hôtel avant de partir pour l\'aéroport'
]
